#!/usr/bin/env python3
"""Generate the embedded macOS strings from the shared Windows/macOS catalog."""
import json
from pathlib import Path
root = Path(__file__).resolve().parent.parent
translations = json.loads((root / 'Shared/localization.json').read_text())
lines = ['// Generated by tools/generate-localizations.py. Edit Shared/localization.json.', 'import Foundation', '', 'enum L10n {', '    static var language = "system"', '    static var isChinese: Bool {', '        language == "zh-Hans" || (language == "system" && (Locale.preferredLanguages.first ?? "en").hasPrefix("zh"))', '    }', '    static let chinese: [String: String] = [']
for key, value in translations.items():
    lines.append(f'        {json.dumps(key, ensure_ascii=False)}: {json.dumps(value, ensure_ascii=False)},')
lines += ['    ]', '}', '', 'func L(_ text: String) -> String {', '    L10n.isChinese ? (L10n.chinese[text] ?? text) : text', '}', '']
(root / 'Sources/Localization.swift').write_text('\n'.join(lines))
